server:
  port: 9191

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka # value will get overriden if passed from external config

spring:
  application:
    name: gateway-service
    
  cloud:
      gateway:
         discovery:
            locator:
               enabled: true
               
         globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: "*"
                allowedHeaders:
                  - content-type
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE

         routes:
         
            - id: master-service
              uri: lb://master-service
              predicates:
              - Path=/masters/**
              
            - id: customer-service
              uri: lb://customer-service
              predicates:
              - Path=/customers/**
            
  profiles:
    active:
      - path # path | header | query are the other spring profiles for other strategies

management:
  endpoints:
    web:
      exposure:
        include: '*'   